-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Trainer CASCADE;
DROP TABLE IF EXISTS Typing CASCADE;
DROP TABLE IF EXISTS Nature CASCADE;
DROP TABLE IF EXISTS Ability CASCADE;
DROP TABLE IF EXISTS Species CASCADE;
DROP TABLE IF EXISTS Pokemon CASCADE;
DROP TABLE IF EXISTS species_ability CASCADE;


