-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Trainer CASCADE;
DROP TABLE IF EXISTS Typing CASCADE;
DROP TABLE IF EXISTS Nature CASCADE;
DROP TABLE IF EXISTS Ability CASCADE;
DROP TABLE IF EXISTS Move CASCADE;
DROP TABLE IF EXISTS Species CASCADE;
DROP TABLE IF EXISTS Pokemon CASCADE;
DROP TABLE IF EXISTS trainer_pokemon CASCADE;
DROP TABLE IF EXISTS species_all_moves CASCADE;
DROP TABLE IF EXISTS species_all_abilities CASCADE;
DROP TABLE IF EXISTS pokemon_current_moves CASCADE;
DROP TABLE IF EXISTS super_effective CASCADE;
DROP TABLE IF EXISTS not_effective CASCADE;
DROP TABLE IF EXISTS immune CASCADE;

